import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { openDB } from 'idb';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API responses for dashboard stats (fast first, then update)
registerRoute(
  ({ url }) => url.pathname.includes('/api/dashboard/stats'),
  new NetworkFirst({
    cacheName: 'api-stats-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 1, maxAgeSeconds: 3600 })
    ]
  })
);

// Cache static images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 30 * 24 * 60 * 60 })
    ]
  })
);

// BACKGROUND SYNC LOGIC
const DB_NAME = 'AccidentAlert_Offline_DB';
const STORE_NAME = 'pending_reports';

self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-reports') {
    event.waitUntil(syncReports());
  }
});

async function syncReports() {
  const db = await openDB(DB_NAME, 1);
  const reports = await db.getAll(STORE_NAME);
  
  for (const report of reports) {
    try {
      // In a real app, you'd call the API here.
      // We simulate a fetch call.
      console.log('Syncing report:', report.id);
      
      const response = await fetch('/api/accidents/sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(report)
      });

      if (response.ok) {
        await db.delete(STORE_NAME, report.id);
        
        // Show notification to user
        self.registration.showNotification('Report Synced!', {
          body: `Accident report ${report.report_id || ''} has been successfully uploaded.`,
          icon: '/pwa-192x192.png'
        });
      }
    } catch (err) {
      console.error('Failed to sync report:', report.id, err);
    }
  }
}
